### ISSUE TITLE
2017-10-20 코드 리뷰

### ISSUE THREAD

**Issue by seungha-kim** [taehoonkong/wpsn-encore#1]
@taehoonkong @sorinies

1. forEach 메소드

https://github.com/taehoonkong/wpsn-encore/blob/2930ea47d5cb7e530b262c1b9bf05515a0cc57e9/api/src/router/api.js#L196

이런 단순 배열 순회의 경우 `for` 구문 대신 배열의 `forEach` 메소드를 사용하면 코드가 더 깔끔해집니다.

2. DELETE 메소드는 idempotent여야 합니다.

https://github.com/taehoonkong/wpsn-encore/blob/2930ea47d5cb7e530b262c1b9bf05515a0cc57e9/api/src/router/api.js#L107-L112

DELETE 메소드를 처리할 때 삭제할 레코드가 있는지 없는지를 확인해야 할 필요는 없습니다. `where` 구문의 조건을 만족하는 레코드가 없는 경우에도 쿼리가 잘 실행됩니다. (물론 아무것도 삭제되지 않습니다.)

그리고 어떤 면에서는 레코드를 확인하지 않는 것이 더 좋은데, DELETE 메소드가 idempotent여야 하기 때문입니다. (여러 번 같은 요청을 보내도 에러가 나지 않아야 하는 성질)

이런 이유에서 `detelePostById` 만 호출하는 쪽을 추천드립니다.

3. geo_x, geo_y

https://github.com/taehoonkong/wpsn-encore/blob/2930ea47d5cb7e530b262c1b9bf05515a0cc57e9/api/migrations/20171012193700_add_post.js#L14-L15

geo_x, geo_y 같은 경우 나중에 검색을 해야 할 필요성이 생길 것으로 예상되는데, VARCHAR 타입으로 저장하면 나중에 검색 기능을 구현할 때 문제가 생길 수 있습니다. 추후 수 타입이나 [공간 정보 타입](https://dev.mysql.com/doc/refman/5.7/en/spatial-datatypes.html)을 사용하는 쪽으로 수정하는 것을 추천드립니다.

**Comment by taehoonkong** [comment]
감사합니다 리뷰해주신 사항 수정하겠습니다~

**Comment by seungha-kim** [comment]
아참 아까 정신이 좀 없었는데 forEach 보다 map을 쓰는게 더 깔끔해집니다!
